apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    app: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: notes-api
      containers:
        - name: api
          image: "{{ .Values.image.repository }}/{{ .Values.api.image }}:{{ .Values.api.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 3000
          env:
            - name: PG_HOST
              value: {{ .Values.postgres.host | quote }}
            - name: PG_DATABASE
              value: {{ .Values.postgres.database | quote }}
            - name: PG_USER
              value: {{ .Values.postgres.user | quote }}
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-creds
                  key: PG_PASSWORD
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: kv
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: kv
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: notes-kv
